name: Build

on:
  push:
    paths-ignore:
      - '.github/*'
      - '*.md'
      - "*.yml"
  pull_request:
    paths-ignore:
      - '.github/*'
      - '*.md'
      - "*.yml"
  workflow_dispatch:
    # allow manual trigger

jobs:
  build:
    name: ${{ matrix.os }} Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: ServerEmus/workflows/.github/workflows/build.yml@main
    with:
      runner: ${{ matrix.os }}
      ProjName: ServerShared
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN   }}