name: Publish Package

on:
  push:
    tags:
      - "release-*"
env:
  ProjName: ServerShared

jobs:
  publish-package:
    uses: ServerEmus/workflows/.github/workflows/package.yml@main
    with:
      ProjName: ServerShared
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN   }}
